### ISSUE TITLE
Create a PureHDF notebook w/ the theme example

### ISSUE THREAD

**Issue by gheber** [HDFGroup/hdf5-tutorial#47]
Multi-threaded writing!

**Comment by Apollo3zehn** [comment]
@gheber Only reading can be multi-threaded, writing is limited to a single thread with PureHDF.

**Comment by gheber** [comment]
First draft in 9f0fee5.

Thanks @Apollo3zehn for the quick turnaround on [1.0.0-beta.3](https://www.nuget.org/packages/PureHDF/1.0.0-beta.3)
